
#define  STRING_ACCOUNT_ABOUT_61	KRESOURCESSTRING(@"account_about_61")

#define  STRING_ACCOUNT_COINNAME_17	KRESOURCESSTRING(@"account_coinname_17")

#define  STRING_ACCOUNT_ME_63	KRESOURCESSTRING(@"account_me_63")

#define  STRING_ACCOUNT_MONEYUNIT_18	KRESOURCESSTRING(@"account_moneyunit_18")

#define  STRING_ACCOUNT_SETTING_60	KRESOURCESSTRING(@"account_setting_60")

#define  STRING_ACCOUNT_TITLE_016	KRESOURCESSTRING(@"account_title_016")

#define  STRING_ACCOUNT_WALLET_16	KRESOURCESSTRING(@"account_wallet_16")

#define  STRING_BACKUPMNEMONI_DESCONE_39	KRESOURCESSTRING(@"backupmnemoni_descone_39")

#define  STRING_BACKUPMNEMONI_DESCTWO_40	KRESOURCESSTRING(@"backupmnemoni_desctwo_40")

#define  STRING_BACKUPMNEMONI_NEXT_41	KRESOURCESSTRING(@"backupmnemoni_next_41")

#define  STRING_BACKUPMNEMONIC_TITLE_38	KRESOURCESSTRING(@"backupmnemonic_title_38")

#define  STRING_COINDETAIL_RECHAGE_01	KRESOURCESSTRING(@"coindetail_rechage_01")

#define  STRING_COINDETAIL_RECHAGE_03	KRESOURCESSTRING(@"coindetail_rechage_03")

#define  STRING_COINDETAIL_WITHDRAW_02	KRESOURCESSTRING(@"coindetail_withdraw_02")

#define  STRING_IDENTIFY_CHECK_05	KRESOURCESSTRING(@"identify_check_05")

#define  STRING_IDENTIFY_CHECKCANCLE_10	KRESOURCESSTRING(@"identify_checkcancle_10")

#define  STRING_IDENTIFY_CHECKDELALERT_08	KRESOURCESSTRING(@"identify_checkdelalert_08")

#define  STRING_IDENTIFY_CHECKOK_09	KRESOURCESSTRING(@"identify_checkok_09")

#define  STRING_IDENTIFY_CHOOSEAGAIN_11	KRESOURCESSTRING(@"identify_chooseagain_11")

#define  STRING_IDENTIFY_NEST_07	KRESOURCESSTRING(@"identify_nest_07")

#define  STRING_IDENTIFY_TIP_06	KRESOURCESSTRING(@"identify_tip_06")

#define  STRING_IDENTIFY_TITLE_04	KRESOURCESSTRING(@"identify_title_04")

#define  STRING_TABBAR_FOCUSON_14	KRESOURCESSTRING(@"tabbar_Focuson_14")

#define  STRING_TABBAR_ACCOUNT_12	KRESOURCESSTRING(@"tabbar_account_12")

#define  STRING_TABBAR_HOME_15	KRESOURCESSTRING(@"tabbar_home_15")

#define  STRING_TABBAR_MESSAGE_13	KRESOURCESSTRING(@"tabbar_message_13")

#define  STRING_USER_EDIT_AREA_68	KRESOURCESSTRING(@"user_edit_area_68")

#define  STRING_USER_EDIT_GENDER_67	KRESOURCESSTRING(@"user_edit_gender_67")

#define  STRING_USER_EDIT_HEADPORTRAIT_64	KRESOURCESSTRING(@"user_edit_headportrait_64")

#define  STRING_USER_EDIT_ID_66	KRESOURCESSTRING(@"user_edit_id_66")

#define  STRING_USER_EDIT_MYCODE_70	KRESOURCESSTRING(@"user_edit_mycode_70")

#define  STRING_USER_EDIT_NAME_65	KRESOURCESSTRING(@"user_edit_name_65")

#define  STRING_USER_EDIT_PICKER_71	KRESOURCESSTRING(@"user_edit_picker_71")

#define  STRING_USER_EDIT_PICKER_72	KRESOURCESSTRING(@"user_edit_picker_72")

#define  STRING_USER_EDIT_SIGNATURE_69	KRESOURCESSTRING(@"user_edit_signature_69")

#define  STRING_WALLET_ACCOUNT_71	KRESOURCESSTRING(@"wallet_account_71")

#define  STRING_WALLET_ACCOUNT_72	KRESOURCESSTRING(@"wallet_account_72")

#define  STRING_WALLET_ACCOUNT_73	KRESOURCESSTRING(@"wallet_account_73")

#define  STRING_WALLET_ASSETS_23	KRESOURCESSTRING(@"wallet_assets_23")

#define  STRING_WALLET_COINNAME_20	KRESOURCESSTRING(@"wallet_coinname_20")

#define  STRING_WALLET_MONEYUNIT_21	KRESOURCESSTRING(@"wallet_moneyunit_21")

#define  STRING_WALLET_RATE_22	KRESOURCESSTRING(@"wallet_rate_22")

#define  STRING_WALLET_TITLE_19	KRESOURCESSTRING(@"wallet_title_19")

#define  STRING_WALLETBACKUP_BTNTITLE_37	KRESOURCESSTRING(@"walletbackup_btntitle_37")

#define  STRING_WALLETBACKUP_DESCONE_35	KRESOURCESSTRING(@"walletbackup_descone_35")

#define  STRING_WALLETBACKUP_DESCTWO_36	KRESOURCESSTRING(@"walletbackup_desctwo_36")

#define  STRING_WALLETBACKUP_EXPORT_37	KRESOURCESSTRING(@"walletbackup_export_37")

#define  STRING_WALLETBACKUP_TITLE_34	KRESOURCESSTRING(@"walletbackup_title_34")

#define  STRING_WALLETNEW_CREATWALLET_33	KRESOURCESSTRING(@"walletnew_creatwallet_33")

#define  STRING_WALLETNEW_DESCONE_25	KRESOURCESSTRING(@"walletnew_descone_25")

#define  STRING_WALLETNEW_DESCTWO_26	KRESOURCESSTRING(@"walletnew_desctwo_26")

#define  STRING_WALLETNEW_KEY_28	KRESOURCESSTRING(@"walletnew_key_28")

#define  STRING_WALLETNEW_KEYAGAIN_29	KRESOURCESSTRING(@"walletnew_keyagain_29")

#define  STRING_WALLETNEW_KEYALERT_30	KRESOURCESSTRING(@"walletnew_keyalert_30")

#define  STRING_WALLETNEW_NAME_27	KRESOURCESSTRING(@"walletnew_name_27")

#define  STRING_WALLETNEW_READ_31	KRESOURCESSTRING(@"walletnew_read_31")

#define  STRING_WALLETNEW_SERICE_32	KRESOURCESSTRING(@"walletnew_serice_32")

#define  STRING_WALLETNEW_TITLE_24	KRESOURCESSTRING(@"walletnew_title_24")

#define  STRING_WITHDRAW_ADRESS_46	KRESOURCESSTRING(@"withdraw_adress_46")

#define  STRING_WITHDRAW_ALERT_58	KRESOURCESSTRING(@"withdraw_alert_58")

#define  STRING_WITHDRAW_ALL_49	KRESOURCESSTRING(@"withdraw_all_49")

#define  STRING_WITHDRAW_BTN_53	KRESOURCESSTRING(@"withdraw_btn_53")

#define  STRING_WITHDRAW_COINTYPE_44	KRESOURCESSTRING(@"withdraw_coinType_44")

#define  STRING_WITHDRAW_COINNAME_45	KRESOURCESSTRING(@"withdraw_coinname_45")

#define  STRING_WITHDRAW_COUNT_47	KRESOURCESSTRING(@"withdraw_count_47")

#define  STRING_WITHDRAW_DESCCOAST_57	KRESOURCESSTRING(@"withdraw_desccoast_57")

#define  STRING_WITHDRAW_DESCONE_55	KRESOURCESSTRING(@"withdraw_descone_55")

#define  STRING_WITHDRAW_DESCTWO_56	KRESOURCESSTRING(@"withdraw_desctwo_56")

#define  STRING_WITHDRAW_HEIGH_52	KRESOURCESSTRING(@"withdraw_heigh_52")

#define  STRING_WITHDRAW_INSTRUCTIONS_54	KRESOURCESSTRING(@"withdraw_instructions_54")

#define  STRING_WITHDRAW_LESS_59	KRESOURCESSTRING(@"withdraw_less_59")

#define  STRING_WITHDRAW_LIMIT_48	KRESOURCESSTRING(@"withdraw_limit_48")

#define  STRING_WITHDRAW_LOW_50	KRESOURCESSTRING(@"withdraw_low_50")

#define  STRING_WITHDRAW_NORMAL_51	KRESOURCESSTRING(@"withdraw_normal_51")

#define  STRING_WITHDRAW_RECORD_43	KRESOURCESSTRING(@"withdraw_record_43")

#define  STRING_WITHDRAW_TITLE_42	KRESOURCESSTRING(@"withdraw_title_42")

